[package]
name = "mimpl"
version = "0.0.0"
authors = ["Nils Eriksson <nils.edvin.eriksson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mimpl"
plugin = true
